server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:tcp://localhost/~/redis}
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.Oracle10gDialect
        show_sql: true
        format_sql: true

  selenium:
    driver:
  async:
    core-pool:
    max-pool:
    q-capacity:
  cache:
    type:
  redis:
    host: ${REDIS_URL:192.168.151.42}
    port: ${REDIS_PORT:6379}
    password:
    stock:
      prefix: stocks

logging:
  level:
    root: INFO