spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/redis
    username: sa
    password:
    driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          #dialect: org.hibernate.dialect.Oracle10gDialect
          #show_sql: true
          format_sql: true
  selenium:
    driver:
  async:
    core-pool:
    max-pool:
    q-capacity:
  cache:
    type:
  redis:
    host: 192.168.151.42
    port: 6379
    password:
